### ISSUE TITLE
with text > 14 chars, eccrypto throws bad decrypt error

### ISSUE THREAD

**Issue by br-arruda** [brunoarruda/PGC#6]
https://github.com/brunoarruda/PGC/blob/88085fde686813a13beaa86dce582de429588018/experimentos/node-bitcoin-key-encryption/app.js#L19

When there are more than 14 characters, the module [eccrypto](https://github.com/bitchan/eccrypto) breaks with this error:

    (node:9164) UnhandledPromiseRejectionWarning: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
        at Decipheriv.final (internal/crypto/cipher.js:164:28)
        at (...)\node-bitcoin-key-encryption\node_modules\eccrypto\browser.js:87:28
        at new Promise (<anonymous>)
        at (...)\node-bitcoin-key-encryption\node_modules\eccrypto\browser.js:68:12
        at (...)\node-bitcoin-key-encryption\node_modules\eccrypto\browser.js:243:12
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
        at startup (internal/bootstrap/node.js:283:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

There was also tests where text was decrypted without erros but the result was corrupt, but I couldn't reproduce the error.

**Comment by br-arruda** [comment]
talvez a mensagem não possa ter mais que 512 ou 256  bits, devido ao uso de ECDSA para assinar hashs de mensagens.

Isso é equivalente a 64 ou 32 bytes de informação. É possível medir o tamanho de uma string em bytes com ```sys.getsizeof``` ([fonte](https://rushter.com/blog/python-strings-and-memory/)). Isso pode ser usado para confirmar se o bug no código inicia quando a string ultrapassa os bytes de uma assinatura.
